[tools]
neovim="0.11.5"
go="latest"
jj="0.36.0"

[env]
GOPATH = "{{config_root}}/go"
GOBIN = "{{config_root}}/go/bin"

[tasks.clean]
run = """
unlink ~/.config/neovim_playground
rm -rf ~/.local/state/neovim_playground
rm -rf ~/.local/share/neovim_playground
rm -rf ~/.local/cache/neovim_playground
"""

[tasks.lazy_sync]
run = """
./start_sandboxed-neovim.sh --headless "+Lazy! sync" +qa
"""

[tasks.aider_grok]
description = "Start Aider with Grok model"
run = "aider --model=openrouter/x-ai/grok-code-fast-1"

[tasks.aider_deepseek]
description = "Start Aider with DeepSeek model"
run = "aider --model=openrouter/deepseek/deepseek-v3.2"

[tasks.aider_haiku]
description = "Start Aider with Claude Haiku model"
run = "aider --model=openrouter/anthropic/claude-haiku-4.5"

[tasks.aider_sonnet]
description = "Start Aider with Claude Sonnet model"
run = "aider --model=openrouter/anthropic/claude-sonnet-4.5"
